stages:
  - lint
  - test

variables:
  COMPOSER_ALLOW_SUPERUSER: "1"

php-lint:
  stage: lint
  image: thecodingmachine/php:8.5-v5-cli@sha256:42215b1a124696a0c5050e68401eb20e168e511d21830f4dfcf1c096beafdb10
  script:
    - php --version
    - find . -name '*.php' -not -path './vendor/*' -exec php -l {} \;

shellcheck:
  stage: lint
  image: koalaman/shellcheck-alpine:stable@sha256:c82fe42504fbc9fc68f15d36638e5ee2324ebb8b94e96a3c4e395bf361c49183
  script:
    - shellcheck --version
    - shellcheck install.sh uninstall.sh usr/local/etc/rc.syshook.d/carp/10-wandhcp usr/local/libexec/dhcpcd-hooks/10-wancarp

pest:
  stage: test
  image: thecodingmachine/php:8.5-v5-cli@sha256:42215b1a124696a0c5050e68401eb20e168e511d21830f4dfcf1c096beafdb10
  variables:
    PHP_EXTENSION_PCOV: "1"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/
  coverage: '/Total:\s*\d+\.\d+\s*%/'
  script:
    - php --version
    - composer --version
    - composer install --no-interaction --prefer-dist --no-progress
    - ./vendor/bin/pest --colors=always --ci --log-junit=junit.xml --coverage --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
    paths:
      - coverage.cobertura.xml
