#!/usr/local/bin/php
<?php

require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if ($type != 'MASTER' && $type != 'BACKUP') {
    log_error("Carp '$type' event unknown from source '{$subsystem}'");
    exit(1);
}

if (!strstr($subsystem, '@')) {
    log_error("Carp '$type' event triggered from wrong source '{$subsystem}'");
    exit(1);
}

list ($vhid, $iface) = explode('@', $subsystem);
$ifkey = get_real_interface();

if ($iface != $ifkey) {
    exit(0);
}

if ($type === "MASTER") {
    log_error("start dhcpcd on interface '$iface' due to CARP event '$type'");

    $mac = sprintf('56:48:46:77:63:%02x', $vhid);
    log_error("Running 'ifconfig $iface ether $mac'");
    exec("ifconfig $iface ether $mac");

    log_error("Running 'dhcpcd -M --noconfigure $iface'");
    exec("dhcpcd -M --noconfigure $iface");
} else {
    log_error("stop dhcpcd on interface '$iface' due to CARP event '$type'");

    log_error("Running 'killall dhcpcd'");
    exec("killall dhcpcd");

    if (!empty(shell_exec("ifconfig $iface | grep hwaddr"))) {
        $mac = shell_exec("ifconfig $iface | grep hwaddr | cut -d' ' -f2");
        log_error("Running 'ifconfig $iface ether $mac'");
        exec("ifconfig $iface ether $mac");
    }
}

