#!/usr/local/bin/php
<?php

require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if ($type != 'MASTER' && $type != 'BACKUP') {
    log_error("Carp '$type' event unknown from source '{$subsystem}'");
    exit(1);
}

if (!strstr($subsystem, '@')) {
    log_error("Carp '$type' event triggered from wrong source '{$subsystem}'");
    exit(1);
}

list ($vhid, $iface) = explode('@', $subsystem);
$ifkey = get_real_interface();

if ($iface != $ifkey) {
    exit(0);
}

if ($type === "MASTER") {
   log_error("start dhcpcd on interface '$iface' due to CARP event '$type'");
    exec("dhcpcd -A --noconfigure " . $iface);
} else {
    log_error("stop dhcpcd on interface '$iface' due to CARP event '$type'");
    exec("dhcpcd -k " . $iface);
}

