#!/usr/local/bin/php
<?php

require_once("config.inc");
require_once("interfaces.inc");
require_once("util.inc");

$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if ($type != 'MASTER' && $type != 'BACKUP') {
    log_error("Carp '$type' event unknown from source '{$subsystem}'");
    exit(1);
}

if (!strstr($subsystem, '@')) {
    log_error("Carp '$type' event triggered from wrong source '{$subsystem}'");
    exit(1);
}

$if_wan = get_real_interface('wan');
$if_opt5 = get_real_interface('opt5');

list ($vhid, $iface) = explode('@', $subsystem);

if ($iface != $if_wan && $iface != $if_opt5) {
    exit(0);
}

# Translate interface name
$ifname = convert_real_interface_to_friendly_interface_name($iface);

if ($type === "MASTER") {
    log_error("start dhcpcd on interface '$iface' due to CARP event '$type'");

    $mac = sprintf('00:00:5e:00:01:%02x', $vhid);
    log_error("Running 'ifconfig $iface ether $mac'");
    exec("ifconfig $iface ether $mac");

    $a_vip = &config_read_array('virtualip', 'vip');
    $vid = array_search($ifname, array_column($a_vip, 'interface'));
    $subnet = $a_vip[$vid]['subnet'];

    log_error("Running 'dhcpcd -b -r $subnet -t 0 --noconfigure $iface'");
    exec("dhcpcd -b -r $subnet -t 0 --noconfigure $iface");
} else {
    log_error("stop dhcpcd on interface '$iface' due to CARP event '$type'");

    log_error("Running 'dhcpcd -x $iface'");
    exec("dhcpcd -x $iface");

    if (!empty(shell_exec("ifconfig $iface | grep hwaddr"))) {
        $mac = rtrim(shell_exec("ifconfig $iface | grep hwaddr | cut -d' ' -f2"));
        log_error("Running 'ifconfig $iface ether $mac'");
        exec("ifconfig $iface ether $mac");
    }
}
